let ActionTypes = {
  REGISTER: 'REGISTRATION_REGISTER',
  STORE_EMAIL_TO_STATE: 'STORE_EMAIL_TO_STATE',
  STORE_TOKEN_TO_STATE: 'STORE_TOKEN_TO_STATE',
  STORE_EMAIL_ERROR: 'STORE_EMAIL_ERROR',
};

export default ActionTypes;
